services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Presiyana8901231871"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
  seq:
     image: datalust/seq
     container_name: seq
     environment:
      ACCEPT_EULA: "Y"
      SEQ_PASSWORD: "Presiyana8901231871"
     ports:
      - "5341"

volumes:
  sqlserverdata: