<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>BuildHub.CommandBuilder</AssemblyName>
    <RootNamespace>BuildHub.CommandBuilder</RootNamespace>
  </PropertyGroup>

</Project>
