CREATE TABLE UNIT_TESTS
(
	ID     INT						NOT NULL IDENTITY(1,1),
	GUID   UNIQUEIDENTIFIER			NOT NULL, 
	NAME   VARCHAR(128)				NOT NULL,
	CONSTRAINT PK_UNIT_TESTS PRIMARY KEY NONCLUSTERED (GUID)
)
GO

CREATE UNIQUE CLUSTERED INDEX UX_UNIT_TESTS_ID
ON UNIT_TESTS
(
	ID
)
GO

CREATE UNIQUE NONCLUSTERED INDEX UX_UNIT_TESTS_GUID
ON UNIT_TESTS
(
	GUID
)
GO